import type { Metadata } from "next";
import { ABeeZee, Inter } from "next/font/google";
import "./globals.css";

const aBeeZee = ABeeZee({
  variable: "--font-abeezee-sans",
  subsets: ["latin"],
  weight: "400",
});

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${aBeeZee.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
